export type PvLeadTemperature = "FROID" | "TIEDE" | "CHAUD" | "TRES_PRIORITAIRE";

export type PvLeadInboxItem = {
  prospectId: string;
  companyName: string | null;
  siren: string | null;
  siret: string | null;
  city: string | null;
  sector: string | null;
  activity: string | null;
  contactName: string | null;
  contactRole: string | null;
  email: string | null;
  phone: string | null;
  domain: string | null;
  sourceMethod: string | null;
  sourceProvider: string | null;
  sourceUrl: string | null;
  identityConfidence: string | null;
  contactScope: string | null;
  verificationSources: string[];
  qualificationStatus: string | null;
  qualificationReason: string | null;
  qualificationScore: number | null;
  pvCommercialQualified: boolean | null;
  pvSiteVerified: boolean | null;
  /** null = pas encore évalué. Ne jamais transformer l'absence de score en « froid ». */
  leadTemperature: PvLeadTemperature | null;
  priorityReason: string | null;
  agentId: string | null;
  workflowId: string | null;
  createdAt: string | null;
  verifiedAt: string | null;
  emailStatus: string | null;
  sentAt: string | null;
  deliveredAt: string | null;
  bounce: boolean | null;
  bounceReason: string | null;
  replyStatus: string | null;
  replyClass: string | null;
  replySummary: string | null;
  lastContactAt: string | null;
  followupsSent: number | null;
  needsCallback: boolean;
  nextAction: string | null;
  nextActionAt: string | null;
  callPending: boolean | null;
  callStatus: string | null;
  callOutcome: string | null;
  meetingStatus: string | null;
  meetingAt: string | null;
  alertPriority: string | null;
  alertChannelsRequired: string[];
  lastNotifiedAt: string | null;
  projectId: string | null;
  projectStatus: string | null;
  puissanceKwc: number | null;
};

export type PvLeadInbox = {
  items: PvLeadInboxItem[];
  total: number;
};
